### ISSUE TITLE
Fix `--cutoff` parameter

### ISSUE THREAD

**Issue by jasmezz** [Darcy220606/AMPcombi#93]
The `--cutoff` parameter currently does not accept floating point numbers (see [here](https://github.com/nf-core/funcscan/actions/runs/7831403916/job/21396828468?pr=332#step:4:167)) which it should, because non-zero values lead to breaking the tool.

**Current behaviour:**
`--cutoff 0.0` --> `ampcombi: error: argument --cutoff: invalid int value: '0.0'`
`--cutoff 0` --> no error

**Desired behaviour:**
`--cutoff 0.0` --> no error
`--cutoff 0` --> no error

**Comment by Darcy220606** [comment]
Thats now fixed in the new version 0.2.0
