### ISSUE TITLE
Add a check for empty files Nonetype upon diamond alignment

### ISSUE THREAD

**Issue by Darcy220606** [Darcy220606/AMPcombi#98]
At the moment ampcombi crashes when no hits where found upon the step of merging the hit summary to teh diamond because of empty files.

**Comment by jasmezz** [comment]
I think is the related error message:
![image](https://github.com/Darcy220606/AMPcombi/assets/73216762/11fd58f1-8d50-4603-9b30-c1204e3ba8e2)

We are getting this for a nf-core/funcscan test with preannotated data (no hits found in sample 1), which causes the pipeline to crash :cry:

**Comment by Darcy220606** [comment]
Its now been addressed in PR https://github.com/Darcy220606/AMPcombi/pull/100
